package basicauth

// UserName type represents a user name
type UserName string

// Secret represents hash of user password stored in file
// generated by bcrypt library
type Secret string

//Password represents user password
type Password string

// SessionToken represents a session token issued
// by SessionKeeper
type SessionToken string

// PasswordKeeper is an interface to whatever password storage
// facility we have.
type PasswordKeeper interface {
	CheckUserPassword(UserName, Password) error
	AddUser(UserName, Password) error
	DelUser(UserName, Password) error
	ChangeUserPassword(UserName, Password, Password) error
	Close() error
}

// TokenKeeper is an interface to whatever token storage we
// have.
type TokenKeeper interface {
	GenerateToken(UserName) (SessionToken, error)
	CheckToken(UserName, SessionToken) error
	DeleteUserSession(UserName) error
	Close() error
}
